"""
Analysis Script for Supply Chain Simulation Logs.

This script analyzes the log files generated by the supply chain simulation,
providing insights into message patterns, route calculations, and system performance.

Usage:
    python analyze_logs.py logs/20241119_153045
    python analyze_logs.py  # Uses most recent log directory
"""

import os
import sys
import pandas as pd
import glob
from pathlib import Path


def find_latest_log_dir(base_dir="logs"):
    """Find the most recent log directory."""
    log_dirs = glob.glob(os.path.join(base_dir, "*"))
    if not log_dirs:
        print(f"No log directories found in {base_dir}")
        return None
    return max(log_dirs, key=os.path.getmtime)


def analyze_messages(log_dir):
    """Analyze message exchange patterns."""
    messages_file = os.path.join(log_dir, "messages.csv")
    
    if not os.path.exists(messages_file):
        print(f"Messages log not found: {messages_file}")
        return
    
    print("\n" + "="*70)
    print("MESSAGE ANALYSIS")
    print("="*70)
    
    df = pd.read_csv(messages_file)
    
    print(f"\nTotal messages: {len(df)}")
    print(f"\nMessages by type:")
    print(df['message_type'].value_counts())
    
    print(f"\nMessages by performative:")
    print(df['performative'].value_counts())
    
    print(f"\nTop senders:")
    print(df['sender'].value_counts().head(10))
    
    print(f"\nTop receivers:")
    print(df['receiver'].value_counts().head(10))
    
    # Message flow analysis
    print(f"\nMessage flow patterns:")
    flow = df.groupby(['sender', 'receiver', 'message_type']).size().reset_index(name='count')
    flow = flow.sort_values('count', ascending=False).head(15)
    print(flow.to_string(index=False))


def analyze_route_calculations(log_dir):
    """Analyze route calculation performance."""
    routes_file = os.path.join(log_dir, "route_calculations.csv")
    
    if not os.path.exists(routes_file):
        print(f"Route calculations log not found: {routes_file}")
        return
    
    print("\n" + "="*70)
    print("ROUTE CALCULATION ANALYSIS")
    print("="*70)
    
    df = pd.read_csv(routes_file)
    
    print(f"\nTotal route calculations: {len(df)}")
    
    print(f"\nCalculations by algorithm:")
    print(df['algorithm'].value_counts())
    
    print(f"\nComputation time statistics (ms):")
    print(df['computation_time_ms'].describe())
    
    if 'algorithm' in df.columns:
        print(f"\nAverage computation time by algorithm:")
        for algo in df['algorithm'].unique():
            algo_df = df[df['algorithm'] == algo]
            print(f"  {algo}: {algo_df['computation_time_ms'].mean():.3f} ms")
    
    print(f"\nCalculations by number of orders:")
    print(df['num_orders'].value_counts().sort_index())
    
    print(f"\nAverage computation time by number of orders:")
    order_stats = df.groupby('num_orders')['computation_time_ms'].agg(['mean', 'std', 'count'])
    print(order_stats)
    
    print(f"\nAverage route metrics:")
    print(f"  Route length: {df['route_length'].mean():.2f} nodes")
    print(f"  Total distance: {df['total_distance'].mean():.2f}")
    print(f"  Total fuel: {df['total_fuel'].mean():.2f}")


def analyze_vehicle_metrics(log_dir):
    """Analyze vehicle performance metrics."""
    vehicles_file = os.path.join(log_dir, "vehicle_metrics.csv")
    
    if not os.path.exists(vehicles_file):
        print(f"Vehicle metrics log not found: {vehicles_file}")
        return
    
    print("\n" + "="*70)
    print("VEHICLE METRICS ANALYSIS")
    print("="*70)
    
    df = pd.read_csv(vehicles_file)
    
    print(f"\nTotal vehicle state snapshots: {len(df)}")
    
    print(f"\nVehicle utilization:")
    vehicle_counts = df['vehicle_jid'].value_counts()
    print(f"  Total vehicles: {len(vehicle_counts)}")
    print(f"  Snapshots per vehicle: {vehicle_counts.describe()}")
    
    print(f"\nAverage fuel level: {df['current_fuel'].mean():.2f}")
    print(f"Average load: {df['current_load'].mean():.2f}")
    
    print(f"\nStatus distribution:")
    if 'status' in df.columns:
        print(df['status'].value_counts())
    
    print(f"\nAverage orders per vehicle:")
    print(f"  Active orders: {df['num_active_orders'].mean():.2f}")
    print(f"  Pending orders: {df['num_pending_orders'].mean():.2f}")


def analyze_inventory(log_dir):
    """Analyze inventory changes."""
    inventory_file = os.path.join(log_dir, "inventory_changes.csv")
    
    if not os.path.exists(inventory_file):
        print(f"Inventory log not found: {inventory_file}")
        return
    
    print("\n" + "="*70)
    print("INVENTORY ANALYSIS")
    print("="*70)
    
    df = pd.read_csv(inventory_file)
    
    print(f"\nTotal inventory changes: {len(df)}")
    
    print(f"\nChanges by agent type:")
    print(df['agent_type'].value_counts())
    
    print(f"\nChanges by product:")
    print(df['product'].value_counts())
    
    print(f"\nChanges by type:")
    print(df['change_type'].value_counts())
    
    print(f"\nTotal quantity moved:")
    print(f"  Sum: {df['quantity'].sum()}")
    print(f"  Average: {df['quantity'].mean():.2f}")


def analyze_orders(log_dir):
    """Analyze order lifecycle."""
    orders_file = os.path.join(log_dir, "order_lifecycle.csv")
    
    if not os.path.exists(orders_file):
        print(f"Order lifecycle log not found: {orders_file}")
        return
    
    print("\n" + "="*70)
    print("ORDER LIFECYCLE ANALYSIS")
    print("="*70)
    
    df = pd.read_csv(orders_file)
    
    print(f"\nTotal order events: {len(df)}")
    
    print(f"\nEvents by type:")
    print(df['event_type'].value_counts())
    
    print(f"\nOrders by product:")
    print(df['product'].value_counts())
    
    print(f"\nTotal quantity ordered:")
    print(f"  Sum: {df['quantity'].sum()}")
    print(f"  Average: {df['quantity'].mean():.2f}")
    
    # Count unique orders
    unique_orders = df['order_id'].nunique()
    print(f"\nUnique orders: {unique_orders}")


def main():
    """Main analysis function."""
    if len(sys.argv) > 1:
        log_dir = sys.argv[1]
    else:
        log_dir = find_latest_log_dir()
        if log_dir is None:
            print("No log directory found. Run simulation first.")
            return
        print(f"Using latest log directory: {log_dir}")
    
    if not os.path.exists(log_dir):
        print(f"Log directory not found: {log_dir}")
        return
    
    print(f"\nAnalyzing logs from: {log_dir}")
    print(f"Log directory: {os.path.basename(log_dir)}")
    
    # Run all analyses
    analyze_messages(log_dir)
    analyze_route_calculations(log_dir)
    analyze_vehicle_metrics(log_dir)
    analyze_inventory(log_dir)
    analyze_orders(log_dir)
    
    print("\n" + "="*70)
    print("ANALYSIS COMPLETE")
    print("="*70)


if __name__ == "__main__":
    main()
